# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: CopyFiles@1
  inputs:
    contents: 'test_nginx'
    targetFolder: $(Build.ArtifactStagingDirectory)

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script 1'

- script: |
    echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
    python -m pip install
    echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
    pip install ansible[azure]
    echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
    pip install setuptools
    echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
    pip install packaging
    echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
  displayName: 'Install tool'

- script: |
    python -V
    pip -V
    ansible --version
  displayName: 'Version check'

- script: ansible-playbook create_azure_vm.yml
  displayName: 'run ansible-playbook'
