#- hosts: localhost
#  tasks:
#    - name: Prepare random postfix
#      set_fact:
#        rpfx: "{{ 1000 | random }}"
#      run_once: yes

- hosts: localhost
#  vars:
#    mysqlserver_name: mysql{{ rpfx }}
  tasks:
    - name: Create MySQL Server
      azure_rm_mysqlserver:
        resource_group: "{{ resource_group.name }}"
        name: "{{ mysql.server_name }}"
        sku:
          name: GP_Gen5_2
          tier: GeneralPurpose
        location: "{{ resource_group.location }}"
        version: 5.6
#        enforce_ssl: True
        enforce_ssl: False
        admin_username: "{{ mysql.username }}"
        admin_password: "{{ mysql.password }}"
        storage_mb: 5120
      register: out
    - debug: msg="{{ out }}"

    - name: Create instance of MySQL Database
      azure_rm_mysqldatabase:
        resource_group: "{{ resource_group.name }}"
        server_name: "{{ mysql.server_name }}"
        name: "{{ mysql.db_name }}"
      register: out
    - debug: msg="{{ out }}"

    - name: Create (or update) MySQL firewall rule
      azure_rm_mysqlfirewallrule:
        resource_group: "{{ resource_group.name }}"
        server_name: "{{ mysql.server_name }}"
        name: rule1
        start_ip_address: 40.121.36.77
        end_ip_address: 40.121.36.77

    - name: Get instance of MySQL Database
      azure_rm_mysqldatabase_facts:
        resource_group: "{{ resource_group.name }}"
        server_name: "{{ mysql.server_name }}"
#        name: "{{ mysql.db_name }}"
      register: out
    - debug: msg="{{ out }}"

