-   name: Create (or update) MySQL firewall rule
    azure_rm_mysqlfirewallrule:
        resource_group: "{{ resource_group.name }}"
        server_name: "{{ mysql.server_name }}"
        name: rule1
        start_ip_address: "{{ groups['myVM'][0] }}"
        end_ip_address: "{{ groups['myVM'][0] }}"
