-   name: Get instance of MySQL Database
    azure_rm_mysqldatabase_facts:
        resource_group: "{{ resource_group.name }}"
        server_name: "{{ mysql.server_name }}"
#        name: "{{ mysql.db_name }}"
    register: out
-   debug: msg="{{ out }}"

