- name: generate ssh key if not exist
  command: ssh-keygen -N '{{ resource_group.name }}' -f ./ssh_key
  
- name: Create VM
  azure_rm_virtualmachine:
    resource_group: '{{ resource_group.name }}'
    name: '{{ virtual_machine.name }}'
    vm_size: Standard_DS1_v2
    admin_username: '{{admin_username}}'
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{admin_username}}/.ssh/authorized_keys
        key_data: "{{lookup('file', './ssh_key.pub') }}"
    network_interfaces: '{{ network_interface.name }}'
    image:
      offer: Debian
      publisher: credativ
      sku: '8'
      version: latest
